name: Kazarnowicz på svenska
favicon: null
layout_spectrum: 0.4887071729172021
typography_spectrum: 0.03280201740562916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.328733543632552
  lightness: 0.7113975347019732
  saturation: 0.4173088052775711
  rhythmicContrast: 0.4730797887314111
purpose: []
