name: Kazarnowicz på svenska
favicon: null
layout_spectrum: 0.9988
typography_spectrum: 0.50466
title: 'Som min urklippsbok, fast på nätet'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaeae8'
    - '#434542'
    - '#ad9579'
    - '#21221c'
    - '#d54c5a'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 1
purpose: []
